name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
env:
  DISTRO: amazonlinux
  DISTRO_FILE: image-amazonlinux.yaml
  IMAGE_NAME: local-amazon-image
  CONTAINER_NAME: amazon
  ARCH: x86_64
  RELEASE: 2.0.20230119.1
  TEST_FILE: amazonlinux.sh
jobs:
  lxc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: whywaita/setup-lxd@v1
      with:
        lxd_version: latest/stable
    - name: Install distrobuilder
      run: |
        sudo ./setup_runner.sh
        echo DISTRO=$DISTRO CONTAINER_NAME=$CONTAINER_NAME DISTRO_FILE=$DISTRO_FILE ARCH=$ARCH

        rm -f lxd.tar.xz rootfs.squashfs
        sudo distrobuilder build-lxd $DISTRO_FILE -o image.architecture=$ARCH -o image.release=$RELEASE
        sudo lxc image import lxd.tar.xz rootfs.squashfs --alias $IMAGE_NAME
        sudo lxc image list

    - name: Launch container
      run: |
        dig -t A google.com 8.8.8.8
        host_ip=$(lxd init --dump | grep ipv4.address | head -1 | cut -d: -f2 | tr -d ' ' | awk -F/ '{print $1}')
        echo $host_ip
        lxc profile show default
        cat /etc/lxc/default.conf
        lxc launch $IMAGE_NAME $CONTAINER_NAME
        lxc profile create nicnet
        ip a
#        lxc config device add $CONTAINER_NAME eth0 nic nictype=bridged parent=br0
        lxc profile add $CONTAINER_NAME nicnet
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'yum -y install bind-utils'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'host google.com'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'dig -t A google.com 8.8.8.8'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'find /'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'ls -l1d /run/systemd/resolve/*'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'ls -la /etc/systemd/resolved.conf.d/dns_servers.conf || true'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'cat /etc/systemd/resolved.conf.d/dns_servers.conf || true'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'ls -la .'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'ls -la /etc'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'mkdir -p /etc'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'echo search lxd >>/run/systemd/resolve/resolv.conf'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'echo nameserver 8.8.8.8 >>/etc/resolv.conf'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'cat /etc/resolv.conf || true'

    - name: Waiting for network
      run: |
        lxc exec $CONTAINER_NAME -- timeout 2m /bin/bash -c 'echo waiting for network; until ping -c 1 google.com &>/dev/null; do sleep 1; done'
        lxc exec $CONTAINER_NAME -- /bin/bash -c 'dig -t A google.com 8.8.8.8'

    - name: Invoke test
      run: |
        lxc file push $TEST_FILE $CONTAINER_NAME/tmp/
        lxc exec $CONTAINER_NAME -- /bin/bash -x /tmp/$TEST_FILE
